#!/usr/bin/env bash
case "${BASH_SOURCE}" in
*/*) pushd "${BASH_SOURCE%/*}" &>/dev/null ;; # Enter the current directory
*) pushd . &>/dev/null ;; # This seems like duplicate work but we need to match the popd later
esac

function bu_activate_impl() 
{
local force=${BU_SOURCE_IS_FORCE:-false}
case "$*" in
*f*)
    force=true
    ;;
esac

# Default top-level module key for standalone BashTab use.
# Downstream projects should set their own BU_TOP_LEVEL_MODULE
# before sourcing their activate script.
export BU_TOP_LEVEL_MODULE="${BU_TOP_LEVEL_MODULE:-bashtab}"

case "$*" in
*e*)
    BU_SOURCE_IS_FORCE="$force" source ./bu_examples_entrypoint.sh
    ;;
*t*)
    BU_SOURCE_IS_FORCE="$force" source ./bu_test_entrypoint.sh
    ;;
*)
    BU_SOURCE_IS_FORCE="$force" source ./bu_entrypoint.sh
    ;;
esac

bu_mark_load_complete
popd &>/dev/null
}

bu_activate_impl "$@"


